### ISSUE TITLE
wrong loop bound in ludcmp?

### ISSUE THREAD

**Issue by SerenaC94** [wsmoses/Polygeist-Script#5]
I was looking at the ludcmp implementation, and I don't understand this line:

https://github.com/wsmoses/Polygeist-Script/blob/d4aafd3e0c74967fdad11ee58cdd64aca9c84c61/polybench-c-4.2.1-beta/linear-algebra/solvers/ludcmp/ludcmp.polymer.in.mlir#L198

According to the map, the lower bound seems to correspond to %arg5 + %0, but in the C version instead it is `for (j = i+1; j < _PB_N; j++)` so it should just be %arg5 + 1 (or I am not able to read MLIR code, that is also possible).

**Comment by wsmoses** [comment]
Let's look at the broader context:

```mlir
#map1 = affine_map<(d0)[s0] -> (-d0 + s0)>
    affine.for %arg5 = 0 to %0 {
      %2 = affine.load %arg4[-%arg5 + symbol(%0) - 1] : memref<?xf64>
      affine.store %2, %1[0] : memref<1xf64>
      affine.for %arg6 = #map1(%arg5)[%0] to %0 {
```

This corresponds to:

```
   for (i = _PB_N-1; i >=0; i--) {
     w = y[i];
     for (j = i+1; j < _PB_N; j++)
```

As MLIR doesn't support loops with negative step sizes, for the outermost loop, Polygeist iterates from the upper bound down to the lower bound.

We can see from the load in between the two for loops that this means that i corresponds to `-%arg5 + symbol(%0) - 1` where `%arg5` is between 0 to `%0`. At the first iteration, this means that i is equal to `symbol(%0) - 1` and `-(symbol(%0) - 1) + symbol(%0) - 1 = 0` at the final iteration, as intended.

Thus the lower bound of the inner loop should start at `i+1 = (-%arg5 + symbol(%0) - 1) + 1 = -%arg5 + symbol(%0)`. If we loop at the lower bound map we see `#map1 = affine_map<(d0)[s0] -> (-d0 + s0)>` with `d0=%arg5` and `s0=%0`. Plugging these in we find `-%arg5+symbol(%0)`, which is indeed the correct answer!

Hope that helps!

**Comment by SerenaC94** [comment]
Thank you! As I suspected, I am still not great at reading MLIR 😄
